[package]
name = "cica"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
iced = "0.13.1"
image = "0.25.9"
moxcms = { version = "0.7.11", features = ["avx512"] }
tokio = "1.48.0"
